### ISSUE TITLE
Breakage with breaks with the Bazel flag `--incompatible_disable_legacy_proto_provider`, to be flipped in Bazel 1.0

### ISSUE THREAD

**Issue by lberki** [bazelbuild/codelabs#11]
The breakage looks like this:

```
ERROR: /var/lib/buildkite-agent/builds/bk-docker-knlk/bazel-downstream-projects/codelabs/proto/logger/BUILD:31:1: in ts_proto_library rule //proto/logger:logger_ts_proto:
--
  | Traceback (most recent call last):
  | File "/var/lib/buildkite-agent/builds/bk-docker-knlk/bazel-downstream-projects/codelabs/proto/logger/BUILD", line 31
  | ts_proto_library(name = 'logger_ts_proto')
  | File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/a3cacd8feec2143defdbcf39e90c9abd/external/npm_bazel_typescript/internal/protobufjs/ts_proto_library.bzl", line 74, in _ts_proto_library
  | fail(("ts_proto_library dep %s must b...))
  | ts_proto_library dep //proto/logger:logger_proto must be a proto_library rule
```

Which indicates that it uses a version of `ts_proto_library` which does not contain https://github.com/bazelbuild/rules_nodejs/pull/925 .

**Comment by aiuto** [comment]
I have no idea why I assigned this to myself. It must have been a drive by accidental click.
